FROM node:16-alpine AS BUILD
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .

FROM node:16-alpine
WORKDIR /frontend
COPY --from=BUILD /frontend ./
EXPOSE 8000
CMD ["npm", "start"]