version: '3.8'

services:
  backend:
    container_name: weatherback
    env_file:
      "./backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile_back
    ports:
      - "9000:9000"
    volumes:
      - backend_vol:/backend
    networks: 
      - weatherapp
  frontend:
    container_name: weatherfront
    build:
      context: ./frontend
      dockerfile: ./Dockerfile_front
    ports:
      - "80:8000"
    volumes:
      - frontend_vol:/frontend
    networks:
      - weatherapp
volumes:
  backend_vol:
  frontend_vol:
networks:
  weatherapp:
