---
- hosts: all

  become: yes
  tasks:

  # Install Docker
  - name: Prerequisites
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg-agent
        - gnupg2
        - lsb-release
        - apt-transport-https
        - software-properties-common
      update_cache: yes
      state: present

  - name: Get Docker apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ansible_system | lower}}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker Engine
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
      state: present
  
  - name: Add user to docker group
    user:
      name: "ubuntu"
      groups: docker
      append: yes

  # Install docker-compose
  - name: Install Python Package Manager
    apt:
      name: python3-pip
      state: present
  
  - name: Install docker-compose
    become_user: ubuntu
    pip:
      name:
        - docker
        - docker-compose